Homework 10
nkokina/HerokuApp_Natasha_Kokina_QA19 pull request #3
Opened 2022-07-14 11:25 UTC by nkokina

2022-07-14 11:55 UTC, voropa requested changes

2022-07-14 11:55 UTC, voropa commented on ContextMenuTest.java
> +        alert.accept();
По заданию нужно проверит текст внутри алерта, а не просто закрыть его

2022-07-14 11:55 UTC, voropa commented on DynamicControlsTests.java
> +    public void dynamicControlsTest() {
Разделите этот тест на 2: один для чекбокса, другой - для инпута

2022-07-14 11:55 UTC, voropa commented on FramesTest.java
> +        System.out.println(frameText);
remove this line

2022-07-14 13:35 UTC, nkokina commented on FramesTest.java
> +        System.out.println(frameText);
15 and 19?

2022-07-15 08:41 UTC, voropa requested changes

2022-07-15 08:41 UTC, voropa commented on ContextMenuTest.java
> +        alert.accept();
Проверить это через Assert, а не вывести его в консоль через System.out ))

2022-07-15 08:42 UTC, voropa commented on FramesTest.java
> +        System.out.println(frameText);
yes

2022-07-17 08:49 UTC, voropa approved these changes

2022-07-17 11:04 UTC, merged